name: Build and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install plugins
        run: node quartz/bootstrap-cli.mjs plugin install

      - name: Build site
        run: node quartz/bootstrap-cli.mjs build

      - name: Deploy
        run: rsync -a --delete public/ /var/www/quartz/
