name: Build and deploy

on:
  push:
    branches: [v5]

jobs:
  build:
    runs-on: nix
    env:
      npm_config_cache: /tmp/npm-cache
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install plugins
        run: node quartz/bootstrap-cli.mjs plugin install

      - name: Build site
        run: node quartz/bootstrap-cli.mjs build

      - name: Deploy
        run: rsync -rl --delete --no-owner --no-group --no-times public/ /var/www/quartz/
